server:
    port: 4156
    # error:
    #     whitelabel:
    #         enabled: false
    #     path: "/error"
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/stockms?createDatabaseIfNotExist=true
        username: root
        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

#server.error.whitelabel.enabled=false
#server.error.path=/error